import { BtnListType, ProjectListType } from "./types";

export const projectsData: ProjectListType[] = [
      {
        id: 16,
        name: "TalentSphere - Full-Stack Interview Platform",
        subHeading: "Collaborative coding interviews and pair programming platform",
        description:
          ` TalentSphere - Full-Stack Interview Platform \nThe ultimate platform for collaborative coding interviews and pair programming.\n\n Highlights\n VSCode-Powered Code Editor (Monaco)\n Clerk Authentication\n 1-on-1 Video Interview Rooms (Stream)\n 100+ Coding Problems\n Dashboard with Live Stats\n Mic & Camera Toggle, Screen Sharing & Recording\n Real-time Chat Messaging\n Secure Code Execution (Piston)\n Auto Feedback & Confetti\n Practice Problems Page\n Room Locking\n Background Jobs (Inngest)\n REST API (Node.js & Express)\n TanStack Query\n Modern UI (DaisyUI + TailwindCSS)\n Easy Deployment\n\nFrontend: React 19, Vite, TailwindCSS 4, DaisyUI, Monaco Editor, TanStack Query, Clerk, Stream Video SDK, Axios\nBackend: Node.js, Express, MongoDB, Mongoose, Clerk Express, Stream Node SDK, Inngest, Piston API\n`,
        demoLink: "https://github.com/Niteshagarwal01/TalentSphere",
        sourceLink: "https://github.com/Niteshagarwal01/TalentSphere",
        techStack: [
          "React",
          "Vite",
          "TailwindCSS",
          "DaisyUI",
          "Monaco Editor",
          "TanStack Query",
          "Clerk",
          "Stream Video SDK",
          "Axios",
          "Node.js",
          "Express",
          "MongoDB",
          "Mongoose",
          "Clerk Express",
          "Stream Node SDK",
          "Inngest",
          "Piston API"
        ],
      },
    {
      id: 15,
      name: "AIvory – Your Smile's Smartest Companion",
      subHeading: "Modern dental appointment booking platform with AI-powered voice assistant and location-based dentist discovery",
      description:
        ` AIvory – Your Smile's Smartest Companion \nModern dental appointment booking platform with AI-powered voice assistant and location-based dentist discovery\n\n Features\n Landing & Authentication: Modern landing page, Clerk auth, Email verification, User profile\n Location-Based Dentist Discovery: Real dentist data from OpenStreetMap, map & list view, dentist details, free booking\n AI Voice Assistant (Premium): Voice-powered dental assistant using Vapi AI, real-time conversations, dental health guidance\n Subscription Plans: Free, AI Basic, AI Pro, managed via Clerk billing\n Admin Dashboard: Dedicated admin panel, manage doctors/appointments, view stats\n UI/UX: Tailwind CSS v4, Shadcn UI, custom animations, dark mode, responsive design\n Database & Backend: PostgreSQL with Neon, Prisma ORM, TanStack Query, server actions\n Tech Stack: Next.js 15.5, React 19, TypeScript 5.0, Tailwind CSS 4.0, Shadcn UI, Clerk, Prisma, Leaflet.js, Vapi AI, Resend, TanStack Query, ICS, Lucide React, Vercel/Sevalla compatible`,
      demoLink: "https://a-ivory-your-smile-s-smartest-compa.vercel.app/",
      sourceLink: "https://github.com/Niteshagarwal01/AIvory--Your-Smile-s-Smartest-Companion",
      techStack: [
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Prisma",
        "Clerk",
        "PostgreSQL",
        "Neon",
        "Leaflet.js",
        "Vapi AI",
        "Resend",
        "TanStack Query",
        "ICS",
        "Lucide React",
        "Shadcn UI",
        "React",
        "Vercel",
        "Sevalla"
      ],
    },
  {
    id: 1,
    name: "Tastify - Spotify of Recipes",
    subHeading: "Modern Recipe Discovery App",
    description:
      "A modern, sleek recipe discovery app with a Spotify-like interface for browsing, discovering, and saving delicious recipes from around the world. Features secure authentication with Clerk, smart search by name or ingredients, detailed step-by-step cooking guides, YouTube video tutorials, favorites system, and 8 beautiful themes (Coffee, Forest, Purple, Ocean, Sunset, Mint, Midnight, Rose Gold). Built with React Native + Expo for cross-platform support, Node.js + Express backend, PostgreSQL database with Drizzle ORM, and TheMealDB API for recipe data.",
    demoLink: "",
    sourceLink: "https://github.com/Niteshagarwal01/Tastify-Spotify-for-Recipes",
    techStack: [
      "React Native",
      "Expo",
      "Node.js",
      "Express",
      "PostgreSQL",
      "Drizzle ORM",
      "Clerk Auth",
      "TheMealDB API",
      "YouTube API",
      "Cross-Platform",
    ],
  },
  {
    id: 2,
    name: "Mirai - AI Marketing Automation Platform",
    subHeading: "Digital Marketing Automation System",
    description:
      "A cutting-edge digital marketing automation platform integrating 12+ APIs to streamline marketing operations. Mirai automates social media posts, photoshoots, and video campaigns, along with smart chatbot agents for intelligent customer engagement. Built using Next.js, Python, LangChain, Google Cloud, VAPI, Chatbase, and Google Cloud with Razorpay payment integration for seamless transactions.",
    demoLink: "",
    sourceLink: "",
    techStack: [
      "Next.js",
      "Python",
      "LangChain",
      "nBn",
      "OpenAI",
      "Google Cloud",
      "VAPI",
      "Chatbase",
      "Razorpay",
      "12+ API Integrations",
    ],
  },
  {
    id: 3,
    name: "ipu_guru - Smart Study Platform",
    subHeading: "AI-Powered Educational Platform [In Development]",
    description:
      "An intelligent study platform currently in development, designed to revolutionize the learning experience for students. ipu_guru will feature AI-driven personalized study plans, smart content recommendations, progress tracking, and collaborative learning tools to help students achieve their academic goals efficiently.",
    demoLink: "UNDER_DEVELOPMENT",
    sourceLink: "UNDER_DEVELOPMENT",
    techStack: [
      "React.js",
      "Next.js",
      "AI/ML",
      "Python",
      "TensorFlow",
      "Vector Databases",
      "Authentication",
    ],
  },
  {
    id: 4,
    name: "Jarvis Assistant",
    subHeading: "Smart Voice Assistant",
    description:
      "A fully functional smart assistant developed in Python that uses speech recognition, text-to-speech, and automation APIs. Jarvis can perform tasks like opening applications, web browsing, answering questions, telling jokes, setting reminders, sending emails, and managing files through voice commands, offering an early glimpse into personal AI development.",
    demoLink: "",
    sourceLink: "https://github.com/Niteshagarwal01/jarvis",
    techStack: [
      "Python",
      "Speech Recognition",
      "NLP",
      "APIs",
      "Automation",
      "AI",
      "Text-to-Speech",
    ],
  },
  {
    id: 5,
    name: "Friday AI Assistant",
    subHeading: "Advanced AI Personal Assistant",
    description:
      "An advanced AI-powered personal assistant inspired by Iron Man's FRIDAY. Built with Python, this intelligent system performs complex tasks, provides smart suggestions, manages schedules, and offers conversational AI capabilities. Features include voice commands, task automation, and integration with various productivity tools.",
    demoLink: "",
    sourceLink: "",
    techStack: [
      "Python",
      "AI",
      "Natural Language Processing",
      "Speech Recognition",
      "Automation",
      "Machine Learning",
    ],
  },
  {
    id: 6,
    name: "Emotion Detection Model",
    subHeading: "AI-Powered Emotion Recognition",
    description:
      "An advanced emotion detection system built using YOLO v4 for real-time facial expression analysis. The model accurately identifies and classifies human emotions from images and video streams, enabling applications in mental health monitoring, user experience research, and interactive systems.",
    demoLink: "",
    sourceLink: "",
    techStack: [
      "Python",
      "YOLO v4",
      "OpenCV",
      "TensorFlow",
      "Computer Vision",
      "Deep Learning",
      "Real-time Processing",
    ],
  },
  {
    id: 7,
    name: "Finding My Self in the Lies",
    subHeading: "Creative Writing & Published Book",
    description:
      "A personal creative project and published book that explores the journey of self-awareness, emotions, and inner conflict through compelling storytelling. The work combines creative writing, emotional intelligence, and introspection to inspire readers to question illusions and find their true selves.",
    demoLink: "https://finding-myself-in-the-lies.netlify.app/",
    sourceLink: "https://github.com/Niteshagarwal01/Finding_myself-in-the-lies",
    techStack: [
      "HTML",
      "CSS",
      "JavaScript"
    ],
  },
  {
    id: 8,
    name: "Delta_Front",
    subHeading: "Futuristic Web Interface",
    description:
      "A futuristic web front-end project showcasing clean UI/UX principles, animations, and responsive layouts. Delta_Front emphasizes minimalistic design combined with cutting-edge frontend technologies, providing a modern user experience inspired by sci-fi aesthetics.",
    demoLink: "https://delta-front-clothing-store.netlify.app/",
    sourceLink: "https://github.com/Niteshagarwal01/Delta_front",
    techStack: [
      "HTML",
      "CSS",
      "JavaScript",
      "Responsive Design",
    ],
  },
  {
    id: 9,
    name: "ARYA - AI Mental Health Platform [In Development]",
    subHeading: "AI & Web3 Mental Health Solution",
    description:
      "An AI-powered mental health solution integrating Web3 elements. Features include an intelligent chatbot (Arya) for emotional support, mood tracking, emergency SOS systems, smart appointment booking, and therapeutic games. ARYA promotes mental well-being through personalized, adaptive AI responses and blockchain-secured data handling.",
    demoLink: "",
    sourceLink: "",
    techStack: [
      "AI",
      "Web3",
      "Blockchain", 
      "React",
      "Node.js",
      "TensorFlow",
      "Natural Language Processing",
      "Smart Contracts",
    ],
  },
  {
    id: 10,
    name: "PsycheCare - AI Mental Health Platform",
    subHeading: "Comprehensive Digital Mental Health Ecosystem",
    description:
      "A comprehensive digital mental health ecosystem powered by AI. Core features include 24/7 emotional support via Arya (chatbot), emergency SOS functionality, personalized mental health treatment plans, therapy appointment booking, medication management tools, and AI-driven insights for tracking mental wellness. PsycheCare aims to provide stigma-free, accessible, and personalized mental healthcare for all.",
    demoLink: "https://pyschecare.netlify.app/",
    sourceLink: "https://github.com/Niteshagarwal01/PYSCHECARE",
    techStack: [
      "AI",
      "Machine Learning",
      "HTML",
      "CSS", 
      "JavaScript", 
      "Node.js",
      "Python",
      "Natural Language Processing",
    ],
  },
  {
    id: 11,
    name: "Constitution Made Easy",
    subHeading: "Educational Platform for Indian Constitution",
    description:
      "An educational platform designed to simplify the Indian Constitution. It uses AI-driven summaries, interactive infographics, and quizzes to make complex legal concepts understandable and accessible for students, exam aspirants, and lifelong learners aiming to deepen their civic knowledge.",
    demoLink: "https://constitution-made-easy.netlify.app/",
    sourceLink: "https://github.com/Niteshagarwal01/Constitution_made_easy",
    techStack: [
      "React", 
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
      "AI Content Generation",
      "MongoDB",
      "Interactive Learning Tools",
    ],
  },
  {
    id: 12,
    name: "VANET - Vehicular Ad-hoc Networks Simulation",
    subHeading: "Vehicle-to-Vehicle Communication Research",
    description:
      "A simulation and research project focused on exploring vehicle-to-vehicle communication (V2V) in dynamic mobile environments. This work models real-world traffic networks, tests AI algorithms for collision prevention, and analyzes the efficiency of VANET protocols in smart cities.",
    demoLink: "https://impact-woad.vercel.app/#home",
    sourceLink: "https://github.com/Niteshagarwal01/IMPACT",
    techStack: [
      "Python",
      "Simulation Tools",
      "Network Protocols",
      "AI Algorithms",
      "Data Analysis",
      "Smart City Technologies",
      "Research Methodologies",
    ],
  },
  {
    id: 13,
    name: "Website Projects",
    subHeading: "Frontend Design & Development Collection",
    description:
      "A curated collection of mini-website projects and UI/UX experiments created while exploring modern frontend development. Projects range from landing pages, portfolios, and e-commerce layouts to interactive animations and component libraries, demonstrating strong frontend design skills.",
    demoLink: "",
    sourceLink: "https://github.com/Niteshagarwal01",
    techStack: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "React",
      "Vue.js",
      "SASS",
      "Figma",
      "UI/UX Design",
      "Responsive Web Design",
    ],
  },
  {
    id: 14,
    name: "Python Practice Projects",
    subHeading: "Automation & Utility Scripts Collection",
    description:
      "A diverse set of Python scripts and mini-projects aimed at automation, daily utilities, data handling, and problem-solving exercises. Includes tasks like file organizers, web scrapers, automation bots, data visualization scripts, and beginner-level AI experiments.",
    demoLink: "",
    sourceLink: "https://github.com/Niteshagarwal01",
    techStack: [
      "Python",
      "Data Science",
      "Web Scraping",
      "Automation",
      "File Handling",
      "Data Visualization",
      "Machine Learning",
    ],
  },

  {
    id: 14,
    name: "AirPiano - Virtual Musical Instrument",
    subHeading: "Gesture-Based Music Creation",
    description:
      "A creative tech project that uses hand gestures to play musical notes without any physical contact. Built using Python, OpenCV, and MediaPipe, AirPiano detects finger positions through a webcam and maps them to musical tones in real-time. This project combines computer vision, sound synthesis, and user interaction to create a touchless, futuristic musical experience.",
    demoLink: "",
    sourceLink: "https://github.com/Niteshagarwal01/AIRPIANO",
    techStack: [
      "Python",
      "OpenCV",
      "MediaPipe",
      "Computer Vision",
      "Sound Synthesis",
      "Real-time Processing",
      "UI/UX Design",
    ],
  },
];

export const BtnList: BtnListType[] = [
  {
    label: "Book",
    link: "https://finding-myself-in-the-lies.netlify.app/",
    icon: "book",
    newTab: true,
  },
  { label: "About", link: "/about", icon: "about", newTab: false },
  { label: "Projects", link: "/projects", icon: "projects", newTab: false },
  { label: "Contact", link: "/contact", icon: "contact", newTab: false },
  {
    label: "Github",
    link: "https://github.com/Niteshagarwal01",
    icon: "github",
    newTab: true,
  },
  {
    label: "LinkedIn",
    link: "https://www.linkedin.com/in/nitesh-agarwal-9a1313317/",
    icon: "linkedin",
    newTab: true,
  },
  {
    label: "Instagram",
    link: "https://www.instagram.com/cosmic_nitesh_/",
    icon: "instagram",
    newTab: true,
  },
  {
    label: "Resume",
    link: "/resume.pdf",
    icon: "resume",
    newTab: true,
  },
];
